### ISSUE TITLE
[BUG]在死亡竞技10秒安全时间内可以拔手榴弹

### ISSUE THREAD

**Issue by KUHHGA** [StarSea-Project/StarSea-GMOD-Server#5]
### 错误类型
- 软件错误 [如lua报错等]

### 描述错误
在准备时间内会安置手榴弹并爆炸 ，还用不了绷带，没开游戏就死。
  
### 复现
复现该问题的步骤：  
1. 喝瓶可乐压压惊
2. 开始死亡竞赛
3. 鼠标滑动  
4. 找到手榴弹
5. 鼠标左键点击，选择
6. 鼠标右键
7. 手雷启动
8. 绑在一个地方
9. 手雷触动
10. boom~爆炸
11. 死了
12. 对手阴间喊马，我嘻嘻哈哈
13. 对手感觉崩溃，我心里美味

### 预期行为
本来应该不能使用任何武器，但选择手雷，左键后可以绑定地方来引爆。
 

### 游戏运行信息  
  - 操作系统: [例如 Windows 10]  
  - gmod版本: [2022.06.10,]

**Comment by shirakaze114** [comment]
@VistowtYueCCan 收到，已通知周同学改进
